# Generated by Django 4.1 on 2022-08-21 07:09

import blog_post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="video_thumbnail",
            field=models.ImageField(
                null=True, upload_to=blog_post.models.blog_video_thumbnail_path
            ),
        ),
    ]
