# Generated by Django 4.1 on 2022-08-21 07:49

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_post", "0003_alter_post_created_alter_post_publish_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publish",
            field=django_jalali.db.models.jDateTimeField(
                default=datetime.datetime(2022, 8, 21, 12, 19, 20, 766755)
            ),
        ),
    ]
