# Generated by Django 4.1 on 2022-08-17 05:44

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                default="hello", max_length=150, verbose_name="username"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(upload_to=accounts.models.profile_picture_path),
        ),
    ]
