# Generated by Django 4.1 on 2022-08-18 05:50

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                default="sutdent-prof.png",
                upload_to=accounts.models.profile_picture_path,
            ),
        ),
    ]
