# Generated by Django 4.1 on 2022-08-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="github",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="instagram",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="telegram",
            field=models.URLField(blank=True, null=True),
        ),
    ]
