# Generated by Django 4.1 on 2022-08-29 13:23

import blog.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=10)),
                ("slug", models.SlugField(max_length=250, unique_for_date="created")),
                ("body", models.TextField()),
                (
                    "video",
                    models.FileField(
                        upload_to=blog.models.blog_video_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(["mp4"])
                        ],
                    ),
                ),
                (
                    "video_thumbnail",
                    models.ImageField(
                        null=True,
                        upload_to=blog.models.blog_video_thumbnail_path,
                        validators=[
                            django.core.validators.validate_image_file_extension
                        ],
                    ),
                ),
                ("publish", models.DateTimeField(null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("upadated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
