# Generated by Django 4.1 on 2022-08-30 08:17

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publish",
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="post",
            unique_together={("slug", "publish")},
        ),
    ]
