# Generated by Django 4.1 on 2022-08-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_post_options_post_enable_comments_post_likes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="noww",
            field=models.CharField(default="h", max_length=250),
            preserve_default=False,
        ),
    ]
