# Generated by Django 4.1 on 2022-08-24 05:30

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_comment_active_alter_post_publish"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="email",
        ),
        migrations.AddField(
            model_name="post",
            name="enable_comments",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="publish",
            field=django_jalali.db.models.jDateTimeField(
                default=datetime.datetime(2022, 8, 24, 10, 0, 41, 49408)
            ),
        ),
    ]
