# Generated by Django 4.1 on 2022-08-31 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_post_noww"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="noww",
        ),
    ]
