# Generated by Django 4.1 on 2022-08-24 05:34

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_remove_comment_email_post_enable_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publish",
            field=django_jalali.db.models.jDateTimeField(
                default=datetime.datetime(2022, 8, 24, 10, 3, 59, 853751)
            ),
        ),
    ]
