# Generated by Django 4.1 on 2022-09-01 23:31

import blog.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0011_alter_post_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ("-publish",),
                "verbose_name": "پست",
                "verbose_name_plural": "پست ها",
            },
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="نویسنده",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(verbose_name="متن پست"),
        ),
        migrations.AlterField(
            model_name="post",
            name="created",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True, verbose_name="زمان ساخته شدن"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="enable_comments",
            field=models.BooleanField(default=True, verbose_name="فعال بود کامنت"),
        ),
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL, verbose_name="لایک ها"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="publish",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name=" زمان انتشار"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=250, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=10,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=250, verbose_name="موضوع"),
        ),
        migrations.AlterField(
            model_name="post",
            name="upadated",
            field=django_jalali.db.models.jDateTimeField(
                auto_now=True, verbose_name="اخرین اپدیت"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="video",
            field=models.FileField(
                upload_to=blog.models.blog_video_path,
                validators=[django.core.validators.FileExtensionValidator(["mp4"])],
                verbose_name="ویدیو",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="video_thumbnail",
            field=models.ImageField(
                upload_to=blog.models.blog_video_thumbnail_path,
                validators=[django.core.validators.validate_image_file_extension],
                verbose_name="کاور ویدیو",
            ),
        ),
    ]
