# Generated by Django 4.1 on 2022-08-24 12:59

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_alter_post_publish_delete_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publish",
            field=django_jalali.db.models.jDateTimeField(
                default=datetime.datetime(2022, 8, 24, 17, 28, 59, 747179)
            ),
        ),
    ]
