# Generated by Django 4.1 on 2022-08-24 13:03

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_alter_post_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publish",
            field=django_jalali.db.models.jDateTimeField(
                default=datetime.datetime(2022, 8, 24, 17, 33, 33, 605367)
            ),
        ),
    ]
