# Generated by Django 4.1 on 2022-09-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=30, verbose_name="نام"),
        ),
    ]
