# Generated by Django 4.1 on 2022-09-04 14:08

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                allow_unicode=True, editable=False, populate_from="name"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name", "slug")},
        ),
    ]
