# Generated by Django 4.1 on 2022-09-05 17:19

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0020_remove_category_parent_category_and_more"),
    ]

    operations = [

    ]
