# Generated by Django 4.1 on 2022-09-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("blog", "0023_mycustomtag_taggedwhatever_alter_post_tags"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TaggedWhatever",
            new_name="TaggedPost",
        ),
        migrations.AlterModelOptions(
            name="taggedpost",
            options={
                "verbose_name": "آیتم برچسب گزاری شده",
                "verbose_name_plural": "آیتم های برچسب گزاری شده",
            },
        ),
        migrations.AlterUniqueTogether(
            name="taggedpost",
            unique_together={("content_type", "object_id", "tag")},
        ),
        migrations.AlterIndexTogether(
            name="taggedpost",
            index_together={("content_type", "object_id")},
        ),
    ]
