# Generated by Django 4.1 on 2022-09-08 11:04

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0024_rename_taggedwhatever_taggedpost_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mycustomtag",
            options={"verbose_name": "Tag", "verbose_name_plural": "Tags"},
        ),
        migrations.AlterModelOptions(
            name="taggedpost",
            options={
                "verbose_name": "tagged item",
                "verbose_name_plural": "tagged items",
            },
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="blog.TaggedPost",
                to="blog.MyCustomTag",
                verbose_name="tags",
            ),
        ),
    ]
