# Generated by Django 4.1 on 2022-09-08 12:19

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0025_alter_mycustomtag_options_alter_taggedpost_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "دسته بندی",
                "verbose_name_plural": "دسته بندی ها",
            },
        ),
        migrations.AlterModelOptions(
            name="mycustomtag",
            options={"verbose_name": "برچسب", "verbose_name_plural": "برچسب ها"},
        ),
        migrations.AlterModelOptions(
            name="taggedpost",
            options={
                "verbose_name": "ایتم برچسب زده",
                "verbose_name_plural": "ایتم های برچسب زده",
            },
        ),
        migrations.AlterField(
            model_name="mycustomtag",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="tags",
                to="blog.category",
                verbose_name="دسته بندی",
            ),
        ),
        migrations.AlterField(
            model_name="mycustomtag",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="mycustomtag",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                max_length=100,
                unique=True,
                verbose_name="عنوان انگلیسی",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=250, verbose_name="عنوان انگلیسی"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="blog.TaggedPost",
                to="blog.MyCustomTag",
                verbose_name="برچسب ها",
            ),
        ),
    ]
